ARG UPSTREAM_IMAGE=ghcr.io/ignisda/ryot:v10.5.0@sha256:a752b6aee5378527b20e69076a3e9bd53dae6b550d2c2d67f7f71c7aadbc69cc
FROM ${UPSTREAM_IMAGE}
LABEL org.opencontainers.image.version="v10.5.0-kv.1" \
      org.opencontainers.image.revision="8cb503e5c86d7afe44b207850206bfa0870653bc"
ENV DISABLE_TELEMETRY=true
